# Generated by Django 5.2.7 on 2025-10-17 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
