# Generated by Django 5.2.7 on 2025-10-08 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        ('tracker', '0002_regenerationsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, default='Anonymous', max_length=100, verbose_name='Your Name/Handle')),
                ('comment', models.TextField(verbose_name='Regeneration Observation/Comment')),
                ('regeneration_status', models.CharField(choices=[('F', 'Fine to Walk (Good Regeneration)'), ('M', 'Moderate Recovery (Trails OK)'), ('P', 'Poor Recovery (Hazardous/Closed)'), ('I', 'Initial Growth (Requires Caution)')], default='I', max_length=1, verbose_name='Current Trail/Regeneration Status')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='feedback_pics/', verbose_name='Upload a picture of the area')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reports', to='tracker.regenerationsite', verbose_name='Regeneration Site')),
            ],
        ),
    ]
