# Generated by Django 5.2.7 on 2025-10-18 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_userfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='picture',
        ),
    ]
